Repository Som-Energia/somenergia-oomakotest, pull requests merged in 2020-11, with the labels that each got.

#46 Modificar text emailAdministradoraPerTitularDesassignacio
  input/correu-emailAdministradoraPerTitularDesassignacio.mako
Labels: enhancement

#47 Add support for semantic ID in report_xml templates and cases. Powere…
  oomako
  testcases.yaml
Labels: core

#49 Add Admin OV as a receptor for activacioM105 and canviPagador templates
  input/correu-activacioM105.mako.yaml
  input/correu-canviPagador.mako.yaml
Labels: enhancement

#42 New comunicat socies template
  input/correu-assambleaSocies.mako
  input/correu-assambleaSocies.mako.yaml
  testcases.yaml
Labels: enhancement

#35 killing payer warning template
  input/correu-killingPayerWarning.mako
  input/correu-killingPayerWarning.mako.yaml
  testcases.yaml
Labels: ATR, enhancement
