Repository Som-Energia/somenergia-oomakotest, pull requests merged in 2022-03, with the labels that each got.

#60 Afegir plantilles powersms
  input/powersms/sms-48hTall.mako
  input/powersms/sms-annex4.mako
Labels: enhancement

#75 Update correu-activacioC105.mako
  input/correu-activacioC105.mako
  input/correu-activacioC205.mako
Labels: ATR

#87 Afegir la llengua com a dades del mako.yaml
  input/correu-primerNoRenovacio.mako.yaml
  input/correu-segonNoRenovacio.mako.yaml
  input/correu-tercerNoRenovacio.mako.yaml
  oomako
  testcases.yaml
Labels: core
