Repository Som-Energia/somenergia-oomakotest, pull requests merged in 2023-01, with the labels that each got.

#115 add the run_scipts empty list
  oomako
Labels: bug, core

#116 add lost field
  input/correu-impagament1erAvis.mako
Labels: bug

#111 Mod m105 mail
  input/correu-activacioM105.mako
  input/correu-activacioM105.mako.yaml
  testcases.yaml
Labels: bug, enhancement
